### ISSUE TITLE
BackupStatus isn't shown in BackupServiceStatus

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1029]
I have a backup-enabled cluster.
There is one backup made, but backup status didn't show up:
```
  status:
    backupServiceStatus:
      backupSize: 0.031
      backups: 1
    conditions:
```
