### ISSUE TITLE
Simple TLS flow for minikube (all servers return error)

### ISSUE THREAD

**Issue by todkap** [coreos/etcd-operator#1099]
I am attempting to craft together an end to end flow for TLS enablement of etcd-operator based upon existing resources in this project.

The current design appears to work fine for non-TLS flows but the moment I try to enable TLS with keys, the connection fails.

> error: nodeAppTesting(example-etcd-cluster-client) ->Error: All servers returned errorresponse: nodeAppTesting(example-etcd-cluster-client) ->undefined

In minikube, I set the following secrets (these pem files are from the tls/certs directory
```
kubectl create secret generic etcd-server-peer-tls --from-file=certs/peer-ca-crt.pem --from-file=certs/peer-crt.pem --from-file=certs/peer-key.pem
kubectl create secret generic etcd-server-client-tls --from-file=certs/client-ca-crt.pem --from-file=certs/client-crt.pem --from-file=certs/client-key.pem
kubectl create secret generic operator-etcd-client-tls --from-file=certs/etcd-ca-crt.pem --from-file=certs/etcd-crt.pem --from-file=certs/etcd-key.pem
```

For the yaml file, I appended the TLS configuration referencing the secrets.
```
apiVersion: "etcd.coreos.com/v1beta1"
kind: "Cluster"
metadata:
  name: "example-etcd-cluster"
spec:
  size: 5
  version: "3.1.4"
  TLS:
    static:
      member:
        peerSecret: etcd-server-peer-tls
        clientSecret: etcd-server-client-tls
      operatorSecret: operator-etcd-client-tls
```

Then in my node app (deployed to the same cluster), I look up the etcd client and provide the pem files (same as what was set in the yaml) as options to the constructor.

```
var http = require('http');
var Etcd = require('node-etcd');
var fs = require('fs');
 
var options = {
    ca:   fs.readFileSync('client-ca-crt.pem'),
    cert: fs.readFileSync('client-crt.pem'),
    key:  fs.readFileSync('client-key.pem')
};

var handleRequest = function(request, response) {
	console.log('Received request for URL: ' + request.url);
	response.writeHead(200);

	var scheme = "https";
	var ipAddress = "example-etcd-cluster-client"
	var port = "2379";

	var connectionAddress = scheme +"://" + ipAddress +":" + port;
	var etcd = new Etcd([connectionAddress] , options );
	etcd.set("nodeAppTesting_"+ scheme+"_"+ipAddress+"_"+port , "mycustomValue");
	etcd.get("nodeAppTesting_"+ scheme+"_"+ipAddress+"_"+port, function(err, res){
		if(err){
			response.write("error: nodeAppTesting("+ ipAddress+") ->"+ err);
			response.write("response: nodeAppTesting("+ ipAddress+") ->"+ res);
			
			response.end();
		}else{
			response.write("nodeAppTesting("+ ipAddress+") ->"+  JSON.stringify(res) ) ;
			response.end();
		}
	});
	

};
var www = http.createServer(handleRequest);
www.listen(8080);
console.log("App up and running on port 8080")
```

If I skip creating the secrets, setting up TLS in the yaml and not pass the options in my node script, things work.
> nodeAppTesting(example-etcd-cluster-client) ->{"action":"get","node":{"key":"/nodeAppTesting_http_example-etcd-cluster-client_2379","value":"mycustomValue","modifiedIndex":19,"createdIndex":19}}

Right now, I cannot tell if there is an issue with the certificates (not likely since the tests pass I assume for this project), there is a limitation with minikube or there issue is related to #1010 that was opened a short time ago.

I am open to trying various debugging suggestions as I have spent the last two days trying various options.    If we can get this resolved, I would like to publish an article on how this works.

**Comment by hongchaodeng** [comment]
@todkap Thanks for reporting.

> there issue is related to #1010 that was opened a short time ago.
Not related.

What operator version are you using?

**Comment by todkap** [comment]
I believe it is image: quay.io/coreos/etcd-operator:v0.2.6

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.2.6
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```
