### ISSUE TITLE
etcd-backup-sidecar does not work with bootkube selfhosted etcd

### ISSUE THREAD

**Issue by rimusz** [coreos/etcd-operator#1107]
took etcd-operator v0.3.0 for a spin with backups to S3, it worked fine.

Then upgraded (operator and cluster) installed selfhosted etcd via bootkube v0.2.4->0.2.6->0.3.0, and there
`kube-etcd-backup-sidecar` gives errors:
```
kube-etcd-backup-sidecar-1481061736-7fbhg backup time="2017-05-18T12:02:58Z" level=warning msg="no reachable member"
kube-etcd-backup-sidecar-1481061736-7fbhg backup time="2017-05-18T12:02:58Z" level=error msg="failed to save snapshot: no reachable member"
kube-etcd-backup-sidecar-1481061736-7fbhg backup time="2017-05-18T12:04:03Z" level=warning msg="failed to create etcd client for pod (kube-etcd-0000): grpc: timed out when dialing"
kube-etcd-backup-sidecar-1481061736-7fbhg backup time="2017-05-18T12:04:08Z" level=warning msg="failed to create etcd client for pod (kube-etcd-0001): grpc: timed out when dialing"
kube-etcd-backup-sidecar-1481061736-7fbhg backup time="2017-05-18T12:04:13Z" level=warning msg="failed to create etcd client for pod (kube-etcd-0003): grpc: timed out when dialing"
```

**Comment by hongchaodeng** [comment]
Hi @rimusz
Thanks for reporting.
Can you give details about how to reproduce this issue?

**Comment by rimusz** [comment]
I'm using https://stackpoint.io built cluster, tested on AWS and GCE clusters, both setups have the same issue. Our clusters get built with etcd-operator v0.2.4.
How to reproduce the issue:
```
1) Build the cluster on AWS/GCE with Container Linux as the OS
2) Change `cluster` to v3.1.4
3) Upgrade operator to v0.2.6 then to v0.3.0
4) Edit `cluster` `kube-etcd`: size to 3 and remove `nodeSelector`
5) create secret/config for AWS credentials as per [operator-level-configuration](https://github.com/coreos/etcd-operator/blob/master/doc/user/backup_config.md#operator-level-configuration)
6) update etcd-operator:
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.3.0
        command:
        - /usr/local/bin/etcd-operator
        - --backup-aws-secret=aws
        - --backup-aws-config=aws
        - --backup-s3-bucket=my-etcd-backup-bucket-name
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
7) update cluster kube-etcd:
apiVersion: etcd.coreos.com/v1beta1
kind: Cluster
metadata:
  name: kube-etcd
  namespace: kube-system
spec:
  size: 3
  version: 3.1.4
  backup:
    backupIntervalInSecond: 60
    maxBackups: 5
    storageType: "S3"
```
You should see now in `kube-etcd-backup-sidecar` logs:
```
kube-etcd-backup-sidecar-3968414973-2jmtl backup time="2017-05-18T14:55:32Z" level=warning msg="no reachable member"
kube-etcd-backup-sidecar-3968414973-2jmtl backup time="2017-05-18T14:55:32Z" level=error msg="failed to save snapshot: no reachable member"
kube-etcd-backup-sidecar-3968414973-2jmtl backup time="2017-05-18T14:56:37Z" level=warning msg="failed to create etcd client for pod (kube-etcd-0000): grpc: timed out when dialing"
kube-etcd-backup-sidecar-3968414973-2jmtl backup time="2017-05-18T14:56:42Z" level=warning msg="failed to create etcd client for pod (kube-etcd-0001): grpc: timed out when dialing"
kube-etcd-backup-sidecar-3968414973-2jmtl backup time="2017-05-18T14:56:47Z" level=warning msg="failed to create etcd client for pod (kube-etcd-0002): grpc: timed out when dialing"
```
