### ISSUE TITLE
Can we able to create AWS IAM rolebased etcd-operator?

### ISSUE THREAD

**Issue by ssubramanian123** [coreos/etcd-operator#1112]
Hi,

I am trying to create jenkins pipeline to deploy vault. As part of etcd-operator need below three steps which involves AWS credentials and config. Since storing AWS credentials in stash is not secure (not good practice), looking for alternate option. Is there any best option to create pipeline for vault or can we use AWS IAM role ? 
````
kubectl create secret generic aws --from-file=credentials --namespace=vault
kubectl create configmap aws --from-file=config --namespace=vault
kubectl create -f etcd/etcd-operator.yaml --namespace=vault
````
````
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
  namespace: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.2.6
        command:
        - /usr/local/bin/etcd-operator
        - --backup-aws-secret=aws
        - --backup-aws-config=aws
        - --backup-s3-bucket=my-test-bucket
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
````

**Comment by hongchaodeng** [comment]
IAM roles are per node, right?
We better rely on k8s to do cluster level management.
Maybe ask this question on k8s upstream?

**Comment by ssubramanian123** [comment]
@hongchaodeng IAM role for etcd-operator cluster. We are configuring vault backup as S3 with below AWS credentials.. Is there any way to use IAM role instead of secret/config?

Current
````command:
        - /usr/local/bin/etcd-operator
        - --backup-aws-secret=aws
        - --backup-aws-config=aws
        - --backup-s3-bucket=my-test-bucket````

Expectation.. something like
````command:
        - /usr/local/bin/etcd-operator
        - --backup-aws-role=myimarole
        - --backup-s3-bucket=my-test-bucket````

**Comment by hongchaodeng** [comment]
How to create a aws client via IAM?

**Comment by ssubramanian123** [comment]
@hongchaodeng in the above use case, I am referring only credential section. Apologies, still if it is not clear. 

As part of above step, we are creating S3 bucket and using "aws" secret/config accessing that S3 bucket.

We can access S3 bucket using IAM role as well, can we use it ?

**Comment by hongchaodeng** [comment]
@ssubramanian123 
If it is easier and valid use case, we are glad to add it.
But we would need some time to do some research on it first.
It would be great if you can submit a PR to POC what it looks like.

**Comment by hongchaodeng** [comment]
ref: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

So latest experiment show that on AWS node a pod can save the effort of setting credentials. Ref: https://github.com/coreos/etcd-operator/pull/1221#issuecomment-311462582

**Comment by hongchaodeng** [comment]
fixed by https://github.com/coreos/etcd-operator/pull/1244

**Comment by ssubramanian123** [comment]
@hongchaodeng can you please share sample etcd-operator file which is using IAM role based?

**Comment by ssubramanian123** [comment]
@hongchaodeng Do we have document to use role based S3 bucket for vault?

**Comment by hongchaodeng** [comment]
> Do we have document to use role based S3 bucket for vault?

You might need to ask vault community?
Maybe I didn't catch your question

**Comment by hongchaodeng** [comment]
This issue is already fixed in https://github.com/coreos/etcd-operator/pull/1297

**Comment by ssubramanian123** [comment]
@hongchaodeng  my question was how to implement this feature.  In etcd-operator, we have steps to use S3 bucket with config and credentials. There is no document to show how to use IAM Role. If this issue is fixed, can you please point out how to modify below etcd-operator config.

````
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
  namespace: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.2.6
        command:
        - /usr/local/bin/etcd-operator
        - --backup-aws-secret=aws
        - --backup-aws-config=aws
        - --backup-s3-bucket=my-test-bucket
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
````
