### ISSUE TITLE
Issues with cluster backing up to AWS EBS

### ISSUE THREAD

**Issue by sunshinekitty** [coreos/etcd-operator#1122]
When creating a new etcd cluster configured to backup to an EBS store the following happens to the cluster:

```
status:
  conditions: null
  controlPaused: false
  currentVersion: ""
  members: {}
  phase: Failed
  reason: 'failed to create backup sidecar Deployment: the server could not find the
    requested resource'
  size: 0
  targetVersion: ""
```

### etcd-operator.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.3.0
        command: 
        - /usr/local/bin/etcd-operator
        - --pv-provisioner=kubernetes.io/aws-ebs
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```

### etcd-cluster.yaml
```
apiVersion: "etcd.coreos.com/v1beta1"
kind: "Cluster"
metadata:
  name: "etcd-cluster"
spec:
  size: 3
  version: "3.1.8"
  backup:
    backupIntervalInSecond: 3600
    maxBackups: 5
    storageType: "PersistentVolume"
    pv:
      volumeSizeInMB: 1024
```

The pvc is created:
```
$ kubectl get pvc 
NAME           STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
etcd-cluster-pvc   Bound     pvc-0e5d0dde-3fce-11e7-8cb1-064d4312e388   1Gi        RWO           6m
$ kubectl get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                      REASON    AGE
pvc-0e5d0dde-3fce-11e7-8cb1-064d4312e388   1Gi        RWO           Delete          Bound     default/etcd-cluster-pvc             6m
```
However there is no deployment created.  Running without the backup section in the cluster.yaml the cluster creates without issues.

Kubernetes version is 1.5
