### ISSUE TITLE
Ignoring healthy cluster

### ISSUE THREAD

**Issue by sstarcher** [coreos/etcd-operator#1141]
Setup:
* 0.3.0 etcd-operator
* etcd self-hosted
* 3 etcd nodes

I modified the cluster configuration to add backup support.  This broke due to a known issue with self-hosted etcd and backups.  I removed the backup information from the cluster config.  My expected result was that the cluster would be happy and the operator would continue to operate. 

Result:
* All 3 pods were still running
* Operator running

but the operator is now ignoring the existing cluster
```
time="2017-05-30T12:44:56Z" level=info msg="ignore failed cluster (kube-etcd). Please delete its TPR" pkg=controller
```

From the thirdpartyresource
```
    controlPaused: false
    currentVersion: 3.1.8
    members:
      ready:
      - kube-etcd-0000
      - kube-etcd-0001
      - kube-etcd-0002
    phase: Failed
    reason: deployments.extensions "kube-etcd-backup-sidecar" not found
    size: 3
    targetVersion: ""
```

The operator marked the cluster as failed even though the cluster itself did not fail.  The failure was on the backup operation.  The cluster itself is still happy and functional.
