### ISSUE TITLE
Disaster recovery fails due to ResourceQuota admission controller rejecting init container in etcd pods

### ISSUE THREAD

**Issue by mlowery** [coreos/etcd-operator#1182]
Preconditions:

* Specify requests and limits (via `spec.pod.resources`) in the etcd cluster object as described [here](https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md)
* Have a `NotBestEffort`-scoped quota in place (see [here](https://kubernetes.io/docs/concepts/policy/resource-quotas/))

It seems the problem is that the init containers added to the etcd pods during recovery have no requests and limits specified. So the recovery etcd pod is rejected by the `ResourceQuota` admission controller since it wants all containers (regular and init) to have resources specified.

Possible solutions:

* Accept limits and requests on these init containers from the user
* Hard-code them
* Document that a `LimitRange` may be required if such a quota is in place

**Comment by hongchaodeng** [comment]
Can you provide more details on how to reproduce it?

**Comment by mlowery** [comment]
@hongchaodeng:

1. Enable [`ResourceQuota` admission controller](https://kubernetes.io/docs/admin/admission-controllers/#resourcequota).
1. Create a `NotBestEffort`-scoped quota in the namespace:

    ```yaml
    apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: high-qos-limit-requests
    spec:
      hard:
        limits.cpu: "8"
        limits.memory: 24Gi
        pods: "8"
        requests.cpu: "8"
        requests.memory: 24Gi
      scopes:
      - NotBestEffort
    ```
2. Specify `spec.pod.resources` in etcd cluster object and let the cluster stabilize.
3. Trigger a disaster recovery. I stumbled upon a disaster recovery accidentally but I assume it can be triggered by deleting all of the etcd pods.
4. Tailing etcd-operator logs shows:

    ```
    msg="all etcd pods are dead. Trying to recover from a previous backup"
    msg="fail to do disaster recovery: failed to create seed member (mlowery-etcd-0002): pods \"mlowery-etcd-0002\" is forbidden: failed quota: high-qos-limit-requests:
    ```

**Comment by mlowery** [comment]
@hongchaodeng:

A `LimitRange` such as the following fixed my problem:

```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
```

However, this was only done because it was easier than modifying the etcd-operator code.
