### ISSUE TITLE
pod policy is no longer passed to backup pod

### ISSUE THREAD

**Issue by sstarcher** [coreos/etcd-operator#1195]
I have not dug into the code, but I'm guessing #1036 broke #916 

```
apiVersion: etcd.coreos.com/v1beta1
kind: Cluster
metadata:
  name: kube-etcd
spec:
  backup:
    backupIntervalInSecond: 3600
    cleanupBackupsOnClusterDelete: false
    maxBackups: 5
    pv:
      volumeSizeInMB: 512
    storageType: PersistentVolume
  pod:
    nodeSelector:
      node-role.kubernetes.io/master: ""
    resources: {}
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
  selfHosted:
    bootMemberClientEndpoint: http://10.x.x.x:12379
  size: 3
  version: 3.1.8
```

kube-etcd-0000
```
Node-Selectors:	node-role.kubernetes.io/master=
Tolerations:	node-role.kubernetes.io/master=:Exists:NoSchedule
```

kube-etcd-backup-sidecar-3045662158-zcr5x
```
Node-Selectors:	<none>
Tolerations:	<none>
```

By duplicating the `pod` spec for nodeSelector and tolerations under `backup` my kube-etcd-backup-sidecar is now on the same node set
```
Node-Selectors:	node-role.kubernetes.io/master=
Tolerations:	node-role.kubernetes.io/master=:Exists:NoSchedule
```

If this is the expected behaviour feel free to close.  As a user I expected the backup pod would be on the same node set as the etcd servers by default.
