### ISSUE TITLE
metrics for etcd cluster objects

### ISSUE THREAD

**Issue by brancz** [coreos/etcd-operator#1197]
The etcd-operator already exposes some Prometheus metrics which is great!

To be able to know the expected number of memers of an etcd cluster, it would be great to expose metrics about the etcd cluster object that exist in the Kubernetes cluster.

For example the Prometheus Operator exposes metrics in this form:

```
prometheus_operator_prometheus_spec_replicas
```

@xiang90 @heyitsanthony 

/cc @fabxc @mxinden @Gouthamve

**Comment by xiang90** [comment]
@brancz the metrics is labeled with prometheus statefulset name?

**Comment by fabxc** [comment]
With the Prometheus resource name, IIRC, as stateful set is that name plus
a common suffix.

**Comment by brancz** [comment]
For example this manifest:

```yaml
apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: k8s
  namespace: tectonic-system
spec:
  replicas: 1
```

Produces this metric:

```
# HELP prometheus_operator_prometheus_spec_replicas Number of expected Prometheus replicas for the Prometheus object.
# TYPE prometheus_operator_prometheus_spec_replicas gauge
prometheus_operator_prometheus_spec_replicas{namespace="tectonic-system",prometheus="k8s"} 1
```

Which is exposed by the Prometheus Operator.
