### ISSUE TITLE
self-hosted s3 backup crash

### ISSUE THREAD

**Issue by sstarcher** [coreos/etcd-operator#1198]
* self-hosted
* version 0.3.2

Initial config:
```
spec:
  pod:
    antiAffinity: false
    etcdEnv: null
    nodeSelector:
      node-role.kubernetes.io/master: ""
    resources: {}
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
  selfHosted:
    bootMemberClientEndpoint: http://10.3.0.200:12379
  size: 3
  version: 3.1.8
```

Added: 
```
backup:
  backupIntervalInSecond: 1800
  maxBackups: 5
  storageType: "S3"
  s3:
    s3Bucket: bucket
```

Logs:
```
time="2017-06-15T14:40:21Z" level=info msg="spec update: from: {3 3.1.8 false 0xc420755f20 <nil> <nil> 0xc420191d10 <nil>} to: {3 3.1.8 false 0xc42095f200 0xc42078e880 <nil> 0xc4202abd00 <nil>}" cluster-name=kube-etcd pkg=cluster
time="2017-06-15T14:40:21Z" level=error msg="failed to update backup policy: resource name may not be empty" cluster-name=kube-etcd pkg=cluster
time="2017-06-15T14:40:21Z" level=info msg="deleting the failed cluster" cluster-name=kube-etcd pkg=cluster
time="2017-06-15T14:40:21Z" level=warning msg="fail to handle event: ignore failed cluster (kube-etcd). Please delete its TPR" pkg=controller
time="2017-06-15T14:40:21Z" level=info msg="deleted pod (kube-etcd-0000)" pkg=gc
time="2017-06-15T14:40:21Z" level=info msg="deleted pod (kube-etcd-0001)" pkg=gc
time="2017-06-15T14:40:21Z" level=info msg="deleted pod (kube-etcd-0002)" pkg=gc
time="2017-06-15T14:40:21Z" level=info msg="deleted service (kube-etcd)" pkg=gc
time="2017-06-15T14:40:21Z" level=info msg="deleted service (kube-etcd-client)" pkg=gc
```
