### ISSUE TITLE
Sidecar backup fails to retain user data

### ISSUE THREAD

**Issue by aaronyoungkash** [coreos/etcd-operator#1223]
Testing with operator 0.3.3 and cluster 3.1.9 we wanted to see what happens when deleting enough cluster pods to break quorum. What we found was the cluster recovered, but all our stored keys were gone. Is this the expected behaviour? If so how would one maintain user data via backups, or is that not possible?

Steps to reproduce:

- Create a key (etcdctl mk foo bar)
- Triggered a sidecar backup via the sidecar /v1/backupnow endpoint
- Delete 75% of the pods
- Operator eventually brings up a new set of pods, which settles into a healthy cluster
- The created key is gone (etcdctl get foo)

This is the cluster configuration yaml:

```
apiVersion: "etcd.coreos.com/v1beta1"
kind: "Cluster"
metadata:
  name: "etcd-cluster"
spec:
  size: 7
  version: "3.1.9"
  backup:
    backupIntervalInSecond: 300
    maxBackups: 5
    storageType: "PersistentVolume"
    pv:
      volumeSizeInMB: 512
```
