### ISSUE TITLE
self-hosted with additional cluster fails to backup

### ISSUE THREAD

**Issue by sstarcher** [coreos/etcd-operator#1277]
I have a self hosted etcd-operator setup 
* version 0.4.1
* etcd version 3.1.8
* k8s 1.6.7

I created a new cluster with the following definition.

```
apiVersion: etcd.coreos.com/v1beta1
kind: Cluster
metadata:
  name: test-etcd
spec:
  TLS:
    static:
      member:
        peerSecret: etcd-peer-tls
        serverSecret: etcd-server-tls
      operatorSecret: etcd-client-tls
  backup:
    autoDelete: false
    backupIntervalInSecond: 300
    maxBackups: 5
    s3:
      awsSecret: aws
      s3Bucket: my-bucket
    storageType: S3
  baseImage: quay.io/coreos/etcd
  version: 3.1.8
```

backup logs
```
kubectl logs -f -n kube-system test-etcd-backup-sidecar-2503026202-vlp7z
2017-07-12 15:39:39.930316 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
time="2017-07-12T15:39:39Z" level=info msg="listening on 0.0.0.0:19999"
time="2017-07-12T15:44:45Z" level=warning msg="failed to create etcd client for pod (test-etcd-0000): grpc: timed out when dialing"
time="2017-07-12T15:44:45Z" level=warning msg="no reachable member"
time="2017-07-12T15:44:45Z" level=error msg="failed to save snapshot: no reachable member"
time="2017-07-12T15:49:50Z" level=warning msg="failed to create etcd client for pod (test-etcd-0000): grpc: timed out when dialing"
time="2017-07-12T15:49:50Z" level=warning msg="no reachable member"
time="2017-07-12T15:49:50Z" level=error msg="failed to save snapshot: no reachable member"
```

Running pods
```
kubectl get pods -n kube-system | grep etcd
etcd-operator-4026352967-0ldrf                                    1/1       Running   1          31m
kube-etcd-0000                                                    1/1       Running   0          28m
kube-etcd-0001                                                    1/1       Running   0          26m
kube-etcd-0002                                                    1/1       Running   0          26m
kube-etcd-network-checkpointer-1ld0b                              1/1       Running   0          31m
kube-etcd-network-checkpointer-lqd6k                              1/1       Running   0          30m
kube-etcd-network-checkpointer-n4jrn                              1/1       Running   0          30m
test-etcd-0000                                                    1/1       Running   0          12m
test-etcd-backup-sidecar-2503026202-vlp7z                         1/1       Running   0          12m
```
