### ISSUE TITLE
When creating a cluster on AWS the GCE-PD storageclass is used

### ISSUE THREAD

**Issue by blakebarnett** [coreos/etcd-operator#1325]
version: 0.4.2
k8s: 1.7.1
helm chart version: 0.4.1

container is configured with:
```
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - /usr/local/bin/etcd-operator
        - --pv-provisioner=kubernetes.io/aws-ebs
        - --analytics=true
```

But the PVC gets created with a storage-class of: `etcd-backup-gce-pd` 

Which it also creates.  I don't see anywhere else to configure this?
