### ISSUE TITLE
Possibility to keep failing to update Cluster status due to version conflict

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1329]
Currently, in each reconcile, we try to update the status. However, if version conflict error happened, we didn't handle it, and it would happen next time as well:
```
	newCluster, err := k8sutil.UpdateClusterTPRObject(c.config.KubeCli.Core().RESTClient(), c.cluster.Metadata.Namespace, newCluster)
	if err != nil {
		return err
	}

	c.cluster = newCluster
```
If there is some change on the TPR/CR object but it is ignored (we ignore not spec change update, e.g. status update, other minor user update), then we would never update local cluster object and it keep failing version conflict.

**Comment by blakebarnett** [comment]
We are hitting this, we need to add
```
spec:
  pod:
    antiAffinity: true
```

To a live cluster and have it reschedule one of the pods that is currently on the same node as another.  Is this possible at all with the current release?

**Comment by hongchaodeng** [comment]
@blakebarnett 
The information you provide above is little. It doesn't sound a valid proof that you have hit the same problem.

If you hit any issue with etcd operator, can you create a new issue, provide details how your env and steps for reproducing it?

**Comment by blakebarnett** [comment]
k8s version: 1.7.7
etcd-operator version: 0.5.1

I verified this happens if the cluster spec is incorrect at any point.  After that, regardless if it's fixed to be a correct spec we get:
`eo-1-etcd-operator-1485813688-zzzmq etcd-operator time="2017-10-02T23:00:07Z" level=warning msg="periodic update CR status failed: failed to update CR status: the server reported a conflict" cluster-name=infra-etcd pkg=cluster`

In the logs and the cluster won't ever change after that. The only way I've found around this situation is to delete the cluster, but obviously we can't in production.

**Comment by hongchaodeng** [comment]
Sounds like it.
Fixing it right now.
@blakebarnett Suggestion for your side: just restart the operator...

**Comment by blakebarnett** [comment]
I tried this, but it doesn't notice anything changed, and if I update the CR again, it starts failing in the same way.

**Comment by hongchaodeng** [comment]
@blakebarnett 
Can you provide more details:

"but it doesn't notice anything changed" and how do you update the CR?

**Comment by blakebarnett** [comment]
After fixing the CR to be correct for example:
```
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  generation: 0
  labels:
    app: eo-1-etcd-operator
    chart: etcd-operator-0.5.1
    heritage: Tiller
    release: eo-1
  name: infra-etcd
spec:
  backup:
    autoDelete: false
    backupIntervalInSecond: 0
    maxBackups: 0
    pv:
      storageClass: ""
      volumeSizeInMB: 512
    storageType: PersistentVolume
  baseImage: quay.io/coreos/etcd
  pod:
    antiAffinity: true
    resources:
      requests:
        cpu: 200m
        memory: 100Mi
  size: 3
  version: 3.2.7
```

...while it's giving us the `periodic update CR status failed` error it keeps giving the error.  If I delete the etcd-operator pod, it starts up fine, doesn't repeat the `periodic update CR status failed`, but also doesn't notice that the CR has been updated properly.  If I change the CR again, by making a trivial modification like changing the memory limit, it noticed the change, and then starts giving the same error in the log again.
