### ISSUE TITLE
Etcd Operator ignores the custom storageClass

### ISSUE THREAD

**Issue by dmyerscough** [coreos/etcd-operator#1389]
I trying to spin up the Etcd Operator with backup on minikube. However, every time I specified a custom storage type the operator kept trying to use "etcd-backup-gce-pd"

```
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "example-etcd-cluster-with-backup"
spec:
  size: 3
  version: "3.1.8"
  backup:
    # short snapshot interval for testing, do not use this in production!
    backupIntervalInSecond: 30
    maxBackups: 5
    storageType: "PersistentVolume"
    pv:
      volumeSizeInMB: 512
      storageClass: standard
```

```
Sep 10 06:22:30 minikube localkube[3755]: E0910 06:22:30.745826    3755 controller.go:405] Claim "default/example-etcd-cluster-with-backup-pvc": Unknown provisioner "kubernetes.io/gce-pd" requested in storage class "etcd-backup-gce-pd"
```
