### ISSUE TITLE
no kind "EtcdCluster" is registered for version "etcd.database.coreos.com/v1beta2"

### ISSUE THREAD

**Issue by ArrH** [coreos/etcd-operator#1391]
Upon the attempt to create example-etcd-cluster.yaml, using Kubernetes UI, I get the following error:
`unable to decode "example-etcd-cluster.yaml": no kind "EtcdCluster" is registered for version "etcd.database.coreos.com/v1beta2"`

Is this an issue or am I missing something in the documentation?

**Comment by hongchaodeng** [comment]
You need to start etcd operator first.
Can you give detailed steps how you encounter this problem?

**Comment by ArrH** [comment]
Yeah, so first I created the deployment using the deployment.yaml: 

`apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.5.1
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
`
This step was completed without any issues. And then I tried to create example-etcd-cluster.yaml. Upon execution of command, I received the error as in the description of the issue

**Comment by ArrH** [comment]
I've tried playing around with the solutions to similar problems people had and reported here, but so far no luck.

**Comment by ArrH** [comment]
UPDATE:

Alright, I tried experimenting more. I thought my K8 RBAC my be the issue (even though my K8 version is 1.6.7  thus lower than 1.7 and according to docs this should not be the case). I've tried creating the following .yaml file:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: etcd-operator
rules:
- apiGroups:
  - etcd.database.coreos.com
  resources:
  - etcdclusters
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
```
But this gave the similar error as described in the issue:
`unable to decode "rbac1.yaml": no kind "ClusterRole" is registered for version "rbac.authorization.k8s.io/v1beta1"`

No idea what going wrong here. My Kubernetes is running on AWS. It was build using the following image: [kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-07-28].

Any help is really appreciated.
