### ISSUE TITLE
etcd-operator restore from s3 needs to know about s3 prefix 

### ISSUE THREAD

**Issue by fanminshi** [coreos/etcd-operator#1402]
Since etcd-operator supports s3 backup with s3 prefix, then restored from prefixed s3 backup also needs to know about prefix; otherwise, restore won't find the correct backup path.

**Comment by fanminshi** [comment]
I took a look of this issue again. I was able to restore a cluster with following steps:

First, kubectl deploy operator with following:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: gcr.io/coreos-k8s-scale-testing/etcd-operator:fanmin
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```

Then create a 3 node etcd cluster named `s3-cluster-backup`:

```yaml
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "s3-cluster-backup"
spec:
  size: 3
  version: "3.1.8"
  backup:
    # short snapshot interval for testing, do not use this in production!
    backupIntervalInSecond: 30
    maxBackups: 5
    storageType: "S3"
    s3:
      s3Bucket: jenkins-etcd-operator
      awsSecret: aws
      prefix: test-prefix
```

Once `s3-cluster-backup` back up its snapshot, I created another etcd cluster called `s3-cluster-backup-b` that restore snapshot from `s3-cluster-backup`:

```yaml
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "s3-cluster-backup-b"
spec:
  size: 3
  version: "3.1.8"
  backup:
    # short snapshot interval for testing, do not use this in production!
    backupIntervalInSecond: 30
    maxBackups: 5
    storageType: "S3"
    s3:
      s3Bucket: jenkins-etcd-operator
      awsSecret: aws
      prefix: test-prefix
  restore:
   backupClusterName: "s3-cluster-backup"
   storageType: "S3"
```

I noticed that cluster restore depends on `s3` spec under `backup` for finding the correct full s3 path of the restoring snapshot. I am unsure if the dependency is intended.

Seen from the `restores-from-previous-s3-backup` spec [example](https://github.com/coreos/etcd-operator/blob/master/doc/user/spec_examples.md#three-members-cluster-that-restores-from-previous-s3-backup) doesn't require the `s3` spec:

```yaml
metadata:
  name: "cluster-a"
spec:
  size: 3
  backup:
    backupIntervalInSecond: 300
    maxBackups: 5
    storageType: "S3"
  restore:
    backupClusterName: "cluster-a"
    storageType: "S3"
```
