### ISSUE TITLE
cannot turn off client cert auth in etcd using v0.5.2 and v3.1.10

### ISSUE THREAD

**Issue by raoofm** [coreos/etcd-operator#1416]
I'm unable to access etcd via LoadBalancer after enabling tls. I thought this might be due to client-cert-auth=true flag  being set. So I tried to disable client auth but the flag is being ignored by etcd as they have logic in place that ignores flag if already set.

2017-09-19 20:01:52.520944 I | pkg/flags: recognized environment variable ETCD_CLIENT_CERT_AUTH, but unused: shadowed by corresponding flag 

https://github.com/coreos/etcd/blob/f1509a102c192035a5467304b34f1226e100d88a/pkg/flags/flag.go#L119
```
if alreadySet[kv[0]] {
			// TODO: exit with error in v3.4
			plog.Warningf("recognized environment variable %s, but unused: shadowed by corresponding flag", kv[0])
			continue
		}
		if strings.HasPrefix(env, prefix+"_") {
			plog.Warningf("unrecognized environment variable %s", env)
		}
```

service.yaml

```
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.etcdCluster.name }}-client-service-lb
  labels:
    app: "{{ template "name" . }}"
    prometheus-app: "{{ template "name" . }}"
    dns: elb-route53
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    dns.dev.io/domainName: {{ .Values.dns | quote }}
{{- if .Values.httpsEnable }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.awsCert | quote }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 2379
{{- end }}
spec:
  selector:
#    app: etcd
    etcd_cluster: {{ .Values.etcdCluster.name }}
  ports:
  - name: client
    port: 2379
    targetPort: 2379
    protocol: TCP
  type: "LoadBalancer"

```

**Comment by hongchaodeng** [comment]
@raoofm 
How does the deployment look like? Why do you want to turn off client-auth ? If this is valid case, we might be provide an option to disable client-auth.

**Comment by raoofm** [comment]
> How does the deployment look like? 

I'm not sure what you need. Do you want me to paste the yaml files.

![image](https://user-images.githubusercontent.com/12846989/30613649-e0431b02-9d56-11e7-8849-69c18b638529.png)

**deployment.yaml**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    operator: etcd
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        name: {{ template "name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
        operator: etcd
    spec:
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command:
        - "/usr/local/bin/etcd-operator"
        - "--pv-provisioner={{ .Values.etcdCluster.backup.provisioner }}"
        {{- range $key, $value := .Values.commandArgs }}
        - "--{{ $key }}={{ $value }}"
        {{- end }}
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.rbacEnable }}
      serviceAccountName: {{ template "name" . }}
{{- end }}
```

> Why do you want to turn off client-auth ?

@hongchaodeng As I need to talk to cluster from any machine using etcdctl or curl to add auth/kv
