### ISSUE TITLE
Restore cluster fails, backing up works

### ISSUE THREAD

**Issue by ArrH** [coreos/etcd-operator#1417]
I am having troubles with restoring the backup. Here is the exact procedure I tried:

On my cluster with all I deployments:

1. Create Rbac rules
2. Create Operator 
3. Create cluster with s3 backup.

Everything worked.

Now, I created a new kubernetes cluster and I wanted to populate with the backup of my old cluster (just to confirm restoration works before an actual disaster occurs.) 

I took the same steps, except that in step 3 I modified the file so it reads as follows:

```
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "cluster-new"
spec:
  size: 3
  backup:
    backupIntervalInSecond: 120
    maxBackups: 5
    storageType: "S3"
    s3:
      s3Bucket: clusters.hz1.peeeks.net-state-backup-bucket
      awsSecret: aws
  restore:
    backupClusterName: "cluster-old"
    storageType: "S3"
```

Where cluster old is the name I defined in the cluster file of the original cluster under the metadata. 

Now, I get the following log in the sidecar:

```
time="2017-09-21T14:20:34Z" level=info msg="listening on 0.0.0.0:19999" 
time="2017-09-21T14:22:34Z" level=info msg="getMaxRev: member cluster-new-0000 revision (1)" 
time="2017-09-21T14:22:34Z" level=info msg="getMaxRev: member cluster-new-0001 revision (1)" 
time="2017-09-21T14:22:34Z" level=info msg="getMaxRev: member cluster-new-0002 revision (1)" 
time="2017-09-21T14:22:34Z" level=info msg="skipped creating new backup: no change since last time" 
```

And no services or deployments of the old cluster are created. Am I missing something?
