### ISSUE TITLE
S3 Backup IAM permissions

### ISSUE THREAD

**Issue by rmenn** [coreos/etcd-operator#1473]
etcd-operator version : 0.6.0
etcd version : 3.1.8

Looks like the operator isnt pickup the IAM permissions from the host while creating the backup

backup config
```
      "backup": {
          "backupIntervalInSecond": 21600,
          "maxBackups": 50,
          "storageType": "S3",
          "s3": {
              "s3Bucket": "backup",
              "prefix": "cluster/backup/",
              "awsSecret": "aws"
          }
},
```
I have created the config as in the docs which say `For AWS k8s users: If credentials file is not given, operator and backup sidecar pods will make use of AWS IAM roles on the nodes where they are deployed` as i would want it to use the IAM
```
kubectl -n kube-system create secret generic aws --from-file=~/.aws/config
```

It just errors out, i have checked the permissions on the IAM it does have `s3:*` on the s3 bucket. Would be great to have an example to work off, in the event i am going down the wrong path.

**Comment by hongchaodeng** [comment]
> It just errors out,

What failed? Can you provide more details?

**Comment by rmenn** [comment]
Here are the logs, it just fails with access denied. 

```
2017-10-03 07:23:22.001814 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
time="2017-10-03T07:23:22Z" level=info msg="listening on 0.0.0.0:19999"
time="2017-10-03T07:23:22Z" level=fatal msg="failed to list s3 bucket: AccessDenied: Access Denied
```

**Comment by hongchaodeng** [comment]
Just to make sure. It is the backup sidecar failed. Right?
Does operator run fine?
Can you check what node is sidecar running on? Does it have iam role setup?

**Comment by rmenn** [comment]
Yes the side car failed. I am actually using bootkube so i assume the sidecar runs on the same nodes as the operator? Is that right? I have tolerations and node selectors on the operator is that enough to assume that the side car would run on the same node as the operator ? or is there additional config for it?

Operator runs fine.

**Comment by hongchaodeng** [comment]
> I am actually using bootkube so i assume the sidecar runs on the same nodes as the operator?

No.

You need to set podPolicy in backup spec.
No docs yet, code: https://github.com/coreos/etcd-operator/blob/master/pkg/apis/etcd/v1beta2/backup.go#L40

```
backup:
  podPolicy:
    nodeSelector: ...
    tolerations: ...

```

**Comment by hongchaodeng** [comment]
Can you check if the node that sidecar is running on has the right IAM role?

**Comment by rmenn** [comment]
Oh man, im going to try this out, i really didnt see this. Would you also be able to let me know what paths are being written to? i know about `var/tmp` for the backup, i also see 

```
failed to open log file "/var/log/pods/9819c1b2-a806-11e7-95b6-0a6074804746/backup_15.log": open /var/log/pods/9819c1b2-a806-11e7-95b6-0a6074804746/backup_15.log: no such file or directory%
```
Is there somewhere i can look this up?

**Comment by rmenn** [comment]
@hongchaodeng thanks so much, i have this working, may i send a PR to add manifest to the example folder so people using bootkube on aws and want to enable backups? Or should that belong in bootkube. 

Closing the issue, but looking forward to your reply

**Comment by hongchaodeng** [comment]
What would the example look like? I think there are already examples for S3 backup and docs for it.

**Comment by rmenn** [comment]
For example this the etcd definition for a self hosted etcd in use with bootkube

```
---
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: kube-etcd
  namespace: kube-system
spec:
  size: 1
  version: "${etcd-version}"
  backup:
    autoDelete: false
    backupIntervalInSecond: 21600
    maxBackups: 50
    pod:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
    s3:
      awsSecret: etcd-region
      prefix: "${cluster-name}/backup"
      s3Bucket: "${s3-bucket}"
    storageType: S3
  pod:
    nodeSelector:
      node-role.kubernetes.io/master: ''
    tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  selfHosted:
    bootMemberClientEndpoint: https://<IP>:12379
  TLS:
    static:
      member:
        peerSecret: etcd-peer-tls
        serverSecret: etcd-server-tls
      operatorSecret: etcd-client-tls
```
