### ISSUE TITLE
How to use configmapKeyRef in etcd cluster manifest

### ISSUE THREAD

**Issue by wwyiwzhang** [coreos/etcd-operator#1534]
Hi there, here is my current template for etcd cluster

```YAML
apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: etcd-cluster
spec:
  size: 3
  pod:
    nodeSelector:
      name: etcd
  version: 3.1.8
  backup:
    backupIntervalInSecond: 300
    maxBackups: 5
    storageType: S3
    s3:
      s3Bucket: temp
      awsSecret: boto
```

How can I use a configmap field reference for `s3Bucket`? Could you show an example? Thanks!
