### ISSUE TITLE
Boot member errors with "failed to find member" after pivot

### ISSUE THREAD

**Issue by jamiehannaford** [coreos/etcd-operator#1552]
I'm running into problems using the `BootMemberClientEndpoint` field. Before the operator is created, I have an etcd member running as a static pod using `hostNetwork=true`. These are its args:

```yaml
--listen-peer-urls=http://127.0.0.1:12380
--advertise-client-urls=http://127.0.0.1:12379
--initial-cluster-state=new
--initial-advertise-peer-urls=http://127.0.0.1:12380
--listen-client-urls=http://127.0.0.1:12379
--initial-cluster=bootstrap=http://127.0.0.1:12380
--name=bootstrap
--data-dir=/var/lib/etcd
```

I then deploy the operator (also `hostNetwork=true`), and send this `EtcdCluster` spec:

```yaml
ClusterSpec{
     Size:    3,
     Version: v3.1.8,
     SelfHosted: SelfHostedPolicy{
          BootMemberClientEndpoint: "http://localhost:12379",
          SkipBootMemberRemoval:    true,
     }
     // snip PodPolicy
}
```

The EtcdCluster is created successfully into a pod called `etcd-cluster-0000`. However, the bootstrap etcd starts to error:

```
rafthttp: failed to find member 55a39bcb338a9147 in cluster a7ef944b95711739
```

For some reason it can't locate the new self-hosted member (ID 55a39bcb338a9147). 

Looking at the relevant [source code](https://github.com/coreos/etcd/blob/master/rafthttp/http.go#L283-L296) in etcd, it says this might happen for two reasons:

1. user starts a remote peer that belongs to a different cluster with the same cluster ID.
2. local etcd falls behind of the cluster, and cannot recognize the members that joined after its current progress.

I don't think it's 1 because the operator uses `--init-cluster=existing`. How would the bootstrap "fall behind of the cluster"?

Operator logs [here](https://gist.github.com/jamiehannaford/9c5c8236200c28c7fe38c08079f7a9f9)
Boot etcd logs [here](https://gist.github.com/jamiehannaford/f5e9c3b22af9c2bfa1d496d4dc613f33)
self-hosted etcd logs [here](https://gist.github.com/jamiehannaford/dd09121ca4dcc9e0618b85ca3c96dbef)
