### ISSUE TITLE
docs: etcd backup/restore IAM roles

### ISSUE THREAD

**Issue by philips** [coreos/etcd-operator#1682]
Users will want to scope credentials down for backup/restore to only the rights that are required. We need to document that scope for users and add it to the [backup](https://github.com/coreos/etcd-operator/blob/master/doc/user/walkthrough/backup-operator.md) and [restore](https://github.com/coreos/etcd-operator/blob/master/doc/user/walkthrough/restore-operator.md) docs.

Example docs

- https://docs.databricks.com/user-guide/cloud-configurations/aws/iam-roles.html
- https://aws.amazon.com/blogs/security/iam-policies-and-bucket-policies-and-acls-oh-my-controlling-access-to-s3-resources/

**Comment by Deshke** [comment]
from https://github.com/coreos/etcd-operator/issues/1729 

kubernetes already defines ec2 iam roles, adding a new rule to the set is easy and does not require any other configuration. the etcd-backup-operator should use these

```yaml

apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster-backup
spec:
  clusterName: etcd-cluster
  storageType: S3
  s3:
    s3Bucket: arn:aws:s3:::my.bucket

```
