### ISSUE TITLE
Feature: use ec2 IAM instance role 

### ISSUE THREAD

**Issue by Deshke** [coreos/etcd-operator#1729]
kubernetes uses IAM instance roles, the etcd-backup-operator should be able to use these. 

```yaml
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster-backup
spec:
  clusterName: etcd-cluster
  storageType: S3
  s3:
    s3Bucket: some.bucket
```
