### ISSUE TITLE
EtcdRestore should take in EtcdCluster reference

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#1770]
Currently, EtcdRestore takes in ClusterSpec in order to restore EtcdCluster. This incurs a problem when the configuration of EtcdCluster to restore is huge, for example labels, ownerRef, TLS policy, pod policy, etc.

In order to simplify the process and reduce duplication, it'd better put a reference to EtcdCluster in EtcdRestore instead:
```yaml
spec:
  s3: ...
  etcdCluster:
    name: example-etcd-cluster
    namespace: etcd-services
```

TODO:
- [x] restore-operator should ensure that there are no etcd pods and services in its namespace before recreating the restored `EtcdCluster` CR.
- [x] update the restore-operator walkthrough
