### ISSUE TITLE
Help with backup thats not working...

### ISSUE THREAD

**Issue by ArcticSnowman** [coreos/etcd-operator#1800]
Attempting to use the etcdbackup of a cluster and I'm getting the following status
``` 'failed to save snapshot (create etcd client failed: no running etcd pods  found)' ```

backup_cr.yaml is 
``` 
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: test2-secrets-etcd-cluster-backup
spec:
  etcdEndpoints: http://test2-secrets-etcd-cluster-client:2379
  storageType: S3
  s3:
    path: gsg-request-service/etcd.backup
    awsSecret: aws
```
Cluster is 
```
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "test2-secrets-etcd-cluster"
spec:
  size: 3
  version: "3.2.11"
```

`kubectl get pods` show the pods running
```
test2-secrets-etcd-cluster-0004         1/1       Running   0          19h
test2-secrets-etcd-cluster-0005         1/1       Running   0          19h
test2-secrets-etcd-cluster-0006         1/1       Running   0          19h
```

I'm using the latest image of etcd-operator...

Any suggestions?
