### ISSUE TITLE
Backup created by etcd-backup-operator is always empty

### ISSUE THREAD

**Issue by tlunven** [coreos/etcd-operator#1885]
Whatever I do backup data is always 24kb and only contains cluster metadata (peerUrls, names etc...) and no data.

Is there something I do wrong ?

kubernetes version : 1.8.4 (created with kops without rbac)
etcd-operator version : 0.8.3
etcd cluster version : 3.2.11

**Backup CR**
```
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster-backup
spec:
  etcdEndpoints: ["http://example-etcd-cluster-client:2379"]
  storageType: S3
  s3:
    # The format of "path" must be: "<s3-bucket-name>/<path-to-backup-file>"
    # e.g: "mybucket/etcd.backup"
    path: <s3 bucket name>/etcd.backup
    awsSecret: aws
```

**etcd-backup-operator logs**
```
time="2018-01-25T15:54:56Z" level=info msg="Go Version: go1.9.2" 
time="2018-01-25T15:54:56Z" level=info msg="Go OS/Arch: linux/amd64" 
time="2018-01-25T15:54:56Z" level=info msg="etcd-backup-operator Version: 0.8.3" 
time="2018-01-25T15:54:56Z" level=info msg="Git SHA: 85c37511" 
time="2018-01-25T15:55:14Z" level=info msg="Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"default", Name:"etcd-backup-operator", UID:"aa2d2d0e-df23-11e7-919a-02336455c52e", APIVersion:"v1", ResourceVersion:"56891709", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' etcd-backup-operator-699c8976df-d2w48 became leader" 
time="2018-01-25T15:55:14Z" level=info msg="starting backup controller" pkg=controller 
time="2018-01-25T16:04:40Z" level=info msg="getMaxRev: endpoint http://example-etcd-cluster-client:2379 revision (1)" 
```

**Resulting backup file**
[etcd-empty-backup.zip](https://github.com/coreos/etcd-operator/files/1664806/etcd-empty-backup.zip)
