### ISSUE TITLE
Can't deploy EtcdCluster on disconnected kubernetes cluster

### ISSUE THREAD

**Issue by timgclark** [coreos/etcd-operator#1894]
Default ImagePullPolicy for initContainer of "Always" prevents deployments in disconnected
kubernetes clusters.

```
apiVersion: v1
kind: Pod
metadata:
    name: test-etcd-0000
  namespace: default
  ownerReferences:
  - apiVersion: etcd.database.coreos.com/v1beta2
    controller: true
    kind: EtcdCluster
    name: test-etcd
...
spec:
...
  initContainers:
  - command: ...
    image: busybox
    imagePullPolicy: Always
```

Results in pod stuck in 'init' state, backoff pulling busybox image, even though image is available locally:

```
docker images |grep busybox
busybox                                                                         latest              5b0d59026729        7 days ago          1.146 MB
```

Kubernetes version: 1.9.2 (via kubeadm)
etcd-operator version: 0.8.2
