### ISSUE TITLE
Creating 2 etcd-cluster with the same name in different namespaces does not seem to work

### ISSUE THREAD

**Issue by thcdrt** [coreos/etcd-operator#1954]
Hello,

I have an etcd operator deployed in my 'default' namespace in 'cluster-wide' mode and I wanted to create 2 etcd-cluster with the name 'etcd-cluster' in different namespaces and only the first cluster created is really deployed.

## Create the first etcd cluster
First I created an etcd cluster with the name 'etcd-cluster' in namespace 'a':
```bash
> kubectl create namespace a
namespace "a" created
> kubectl create -f etcd-cluster.yaml -n a
etcdcluster "etcd-cluster" created
> kubectl get etcdclusters.etcd.database.coreos.com -n a
NAME           AGE
etcd-cluster   32s
> kubectl get all -n a
NAME                         READY     STATUS    RESTARTS   AGE
po/etcd-cluster-6dwrbmfffk   1/1       Running   0          41s
po/etcd-cluster-s52snxd6b9   1/1       Running   0          25s
po/etcd-cluster-sg6zd495xl   1/1       Running   0          33s

NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
svc/etcd-cluster          ClusterIP   None             <none>        2379/TCP,2380/TCP   41s
svc/etcd-cluster-client   ClusterIP   172.16.159.216   <none>        2379/TCP            41s
```

Operator logs:
```bash
time="2018-04-17T09:40:04Z" level=info msg="creating cluster with Spec:" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:04Z" level=info msg="{" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:04Z" level=info msg="    \"size\": 3," cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:04Z" level=info msg="    \"repository\": \"quay.io/coreos/etcd\"," cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:04Z" level=info msg="    \"version\": \"3.1.8\"" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:04Z" level=info msg="}" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:04Z" level=info msg="cluster created with seed member (etcd-cluster-gmcl4r9gj2)" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:05Z" level=info msg="start running..." cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:13Z" level=info msg="Start reconciling" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:13Z" level=info msg="running members: etcd-cluster-gmcl4r9gj2" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:13Z" level=info msg="cluster membership: etcd-cluster-gmcl4r9gj2" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:13Z" level=info msg="added member (etcd-cluster-fj6d7cd2f5)" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:13Z" level=info msg="Finish reconciling" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:21Z" level=info msg="Start reconciling" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:21Z" level=info msg="running members: etcd-cluster-fj6d7cd2f5,etcd-cluster-gmcl4r9gj2" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:21Z" level=info msg="cluster membership: etcd-cluster-gmcl4r9gj2,etcd-cluster-fj6d7cd2f5" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:21Z" level=info msg="added member (etcd-cluster-bzfqz8mw2g)" cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:40:21Z" level=info msg="Finish reconciling" cluster-name=etcd-cluster pkg=cluster
```

## Create the second etcd cluster
Then I tried to create an other etcd cluster with the same name 'etcd-cluster' in namespace 'b':
```bash
> kubectl create namespace b
namespace "b" created
> kubectl create -f etcd-cluster.yaml -n b
etcdcluster "etcd-cluster" created
> kubectl get etcdclusters.etcd.database.coreos.com -n b
NAME           AGE
etcd-cluster   35s
> kubectl get all -n b
No resources found.
```

Operator logs:
```bash
time="2018-04-17T09:43:12Z" level=warning msg="all etcd pods are dead." cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:43:20Z" level=warning msg="all etcd pods are dead." cluster-name=etcd-cluster pkg=cluster
time="2018-04-17T09:43:28Z" level=warning msg="all etcd pods are dead." cluster-name=etcd-cluster pkg=cluster
```

### etcd-cluster.yaml content
```yaml
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "etcd-cluster"
  annotations:
     etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: "3.1.8"
```

### etcd-operator.yaml content
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator:v0.9.1
        command:
        - etcd-operator
        - -cluster-wide # This allows to create etcd cluster in different namespace
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
```

## Conclusion
This is not a big deal since suffixing the cluster name with the namespace fix the issue and then it works like a charm ! But I just would like to know if this is the desired behavior or not.
