### ISSUE TITLE
S3 custom endpoint is DNS based and is not resolvable

### ISSUE THREAD

**Issue by arunvelsriram** [coreos/etcd-operator#1980]
When using custom endpoint for S3, `etcd-backup-operator` is accessing the buckets with DNS based URL. For example:

If `endpoint = http://s3-minio:9000/`  and `bucket = test` then the resulting URL for accessing the bucket is formed as `http://test.s3-minio:9000`.

DNS resolution fails for this URL as it does not exist.

#### EtcdBackup spec I used:
```
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster-backup
spec:
  etcdEndpoints: ["http://test-etcd-cluster-client:2379"]
  storageType: S3
  s3:
    path: test/backup
    awsSecret: minio
    endpoint: http://s3-minio:9000/
```

I went through the issues and pull requests related to S3 custom endpoint and couldn't find a way to configure `etcd-backup-operator` to use path based S3 bucket URL like `http://s3-minio:9000/test`.

Is there a way to force `etcd-backup-operator` to use path-based URL?
