### ISSUE TITLE
ETCD backup policy is not working

### ISSUE THREAD

**Issue by kannanvr** [coreos/etcd-operator#2031]
I understood that version 0.8.4 onwards ETCD backup policy is working. I have tested the version 0.9.3 and other version as well. It seems ETCD backup policy is not working.

Following is my backup CRD yaml file
```
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster-backup
  namespace: rook-ceph
spec:
  etcdEndpoints:
  - https://127.0.0.1:2379
  clientTLSSecret: "etcd-peer-tls3"
  storageType: S3
  backupPolicy:
    timeoutInSecond: 30
  s3:
    # The format of "path" must be: "<s3-bucket-name>/<path-to-backup-file>"
    # e.g: "mybucket/etcd.backup"
    path: my-store-external/kannan/etcd.backup-1
    awsSecret: aws1
    endpoint: http://kannan.svc.cluster.local
```
It is able to take the backup of ETCD snapshot and push it to S3 first time. But further it is not triggering to take the backup.

Kindly let me know whether my configuration is wrong or any problem on the etcd-backup operator
