### ISSUE TITLE
what is the form of The resource EtcdBackup‘s attribute BackupSpec’s attribute ClientTLSSecret?

### ISSUE THREAD

**Issue by xdhuxc** [coreos/etcd-operator#2040]
type BackupSpec struct {
    EtcdEndpoints []string `json:"etcdEndpoints,omitempty"`
    StorageType BackupStorageType `json:"storageType"`
    BackupPolicy *BackupPolicy `json:"backupPolicy,omitempty"`
    BackupSource `json:",inline"`
    ClientTLSSecret string `json:"clientTLSSecret,omitempty"`
}
I am using the resource EtcdBackup-operator to backup my etcd cluster, but I do not known the form of ClientTLSSecret in yaml, it is a confusing string, why not a clearly ClientTLSSecret struct?Can you gave me a example with clientTLSSecret in yaml or json form? Thank you!

**Comment by lancehudson** [comment]
It is the name of the secret containing the TLS cert, EX:

`
apiVersion: "etcd.database.coreos.com/v1beta2"
    kind: "EtcdBackup"
    metadata:
      generateName: etcd-backup-
    spec:
      etcdEndpoints: ["https://vault-etcd-client:2379"]
      clientTLSSecret: vault-etcd-client-tls
      s3:
        awsSecret: ${aws_backup_creds_secret_name}
        path: ${aws_s3_bucket.vault.bucket}/vault.backup.<NOW>
      storageType: S3
      backupPolicy:
        timeoutInSecond: 600
`

**Comment by hexfusion** [comment]
@xdhuxc is this what you are looking for?

https://github.com/coreos/etcd-operator/blob/aeb3e3e0835ec5135cfe50340f59853b5b6fc407/pkg/apis/etcd/v1beta2/backup_types.go#L74-L80

**Comment by alaypatel07** [comment]
@herbalizer404 you need to create a secret with proper certificates and give the name of the secret in the spec.clientTLSSecret field. If you deployed the etcd cluster with tls from this [resource](https://github.com/coreos/etcd-operator/blob/master/doc/user/cluster_tls.md#operatorsecret) then the value of operatorSecret in your EtcdCluster CR will work in spec.clientTLSSecret field.

**Comment by xuanzhong** [comment]
Same issue here, with the secret in the spec:
kubectl describe EtcdBackup example-etcd-cluster-backup
Name:         example-etcd-cluster-backup
Namespace:    vault
Labels:       <none>
Annotations:  <none>
API Version:  etcd.database.coreos.com/v1beta2
Kind:         EtcdBackup
Metadata:
  Creation Timestamp:  2019-02-21T19:55:33Z
  Generation:          1
  Resource Version:    3511295
  Self Link:           /apis/etcd.database.coreos.com/v1beta2/namespaces/vault/etcdbackups/example-etcd-cluster-backup
  UID:                 a5c69b6d-3612-11e9-9386-066aeaf9a624
Spec:
  Client TLS Secret:  etcd-client-tls
  Etcd Endpoints:
    https://etcd-cluster-client:2379
  S 3:
    Aws Secret:  aws
    Path:        mys3/etcd.backup
  Storage Type:  S3
Status:
  Reason:     failed to save snapshot (create etcd client failed: failed to get etcd client with maximum kv store revision: could not create an etcd client for the max revision purpose from given endpoints ([https://etcd-cluster-client:2379]))
  Succeeded:  false
Events:       <none>

**Comment by alaypatel07** [comment]
@xuanzhong Can you `kubectl describe` the etcd cluster you are trying to backup?

**Comment by xuanzhong** [comment]
@alaypatel07 I solved the issue by changing Etcd Endpoints to be
https://etcd-cluster-client.default.svc:2379
It has to include the namespace and svc, which is not documented anywhere.

**Comment by alaypatel07** [comment]
@xuanzhong that is exactly why I asked you to describe the CR. The CR Status has a field called `serviceName` which should be the endpoint, documented in code [here](https://github.com/coreos/etcd-operator/blob/4aea72218031b976866f3303fe614f6714a7cf98/pkg/apis/etcd/v1beta2/status.go#L54). But you are right we need better documentation, even I had some questions regarding the `endpoints` field, which I could not find answers to, when I first started.

**Comment by jurgenweber** [comment]
I have taken on all the suggestions in this issue and I still have the problem:

```
---
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  annotations:
    etcd.database.coreos.com/scope: clusterwide
  name: vault-etcd-cluster-backup
  namespace: devops
spec:
  backupPolicy:
    # 0 > enable periodic backup
    backupIntervalInSecond: 3600
    maxBackups: 12
  clientTLSSecret: etcd-client-tls
  etcdEndpoints: ["https://vault-etcd-cluster-client.secrets.svc:2379"]
  storageType: S3
  s3:
    # The format of "path" must be: "<s3-bucket-name>/<path-to-backup-file>"
    # e.g: "mybucket/etcd.backup"
    path: au-com-example-vault/backup
    awsSecret: etcd-vault-aws-backup-user
```

error:
```
failed to save snapshot (create etcd client failed: failed to get etcd client with maximum kv store revision: could not create an etcd client for the max revision purpose from given endpoints ([https://vault-etcd-cluster-client.secrets.svc:2379]))
```

I have deleted the backup resource and restored it, I have deleted the backup operator pod just in case and none of this has helped.
