### ISSUE TITLE
Etcd Members don't have a persistent storage identity

### ISSUE THREAD

**Issue by yanniszark** [coreos/etcd-operator#2049]
**Steps to reproduce:**

1. Create an EtcdCluster that uses PersistentVolumes
```yaml
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "example-etcd-cluster"
spec:
  size: 3
  pod:
    persistentVolumeClaimSpec:
      storageClassName: default
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
```
2. Delete a member of the cluster: `kubectl delete <pod_name>`
3. Etcd operator creates a new Pod to replace the deleted one

**Video Footage:** https://www.youtube.com/watch?v=pYyqDs1piG8&feature=youtu.be

**What I expected to happen:**
The new member should get the PV of the deleted one.

**What happened:**
The new member got a new, empty PersistentVolume.

**Why this is a problem:**
Pod deletes happen in Kubernetes even without user error.
For example, draining a node will cause Pods on the node to be deleted.
New members of etcd should get the PV of an old member, if it exists.
StatefulSet already handles this.
