### ISSUE TITLE
Restore etcd backup to a different namespace

### ISSUE THREAD

**Issue by jungopro** [coreos/etcd-operator#2055]
Hello

I'm trying to perform a restore to an etcd cluster **in a different namespace than the operator** and fails. I read through the docs and couldn't find the exact spec to make it work.

**Scenario**
- operator in the `default` namespace
- cluster in `mp-temp` namespace

Backup worked great using the following method:

- create the `aws secret` and the `backup_cr.yaml` in the same namespace **as the operator** (`default`)
- modified `backup_cr.yaml` to include the full cluster path:
```yaml
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster-backup
spec:
  etcdEndpoints: [http://mp-etcd-client.mp-temp.svc.cluster.local:2379]
  storageType: S3
  s3:
    # The format of "path" must be: "<s3-bucket-name>/<path-to-backup-file>"
    # e.g: "mybucket/etcd.backup"
    path: "mybucket/etcd.backup"
    awsSecret: aws
```

The restore process, not so great:

- re-created the cluster in the `mp-temp` namespace:
```bash
$ kg pod -n mp-temp -l app=etcd
NAME                 READY   STATUS    RESTARTS   AGE
mp-etcd-8pzxtltnj4   1/1     Running   0          48m
mp-etcd-cn6khprk55   1/1     Running   0          49m
mp-etcd-lvdfwlsjj2   1/1     Running   0          49m
```

- tried running the restore in both namespaces with different specs but failed:
```yaml
piVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdRestore"
metadata:
  # The restore CR name must be the same as spec.etcdCluster.name
  name: mp-etcd
spec:
  etcdCluster:
    # The namespace is the same as this EtcdRestore CR
    name: mp-etcd
    namespace: mp-temp
  backupStorageType: S3
  s3:
    # The format of "path" must be: "<s3-bucket-name>/<path-to-backup-file>"
    # e.g: "mybucket/etcd.backup"
    path: "mybucket/etcd.backup"
    awsSecret: aws
```

- operator logs:
```bash
time="2019-02-22T13:38:14Z" level=error msg="error syncing restore request (default/mp-etcd): prepare seed failed: failed to get reference EtcdCluster(default/mp-etcd): etcdclusters.etcd.database.coreos.com \"mp-etcd\" not found" pkg=controller
time="2019-02-22T13:39:38Z" level=error msg="error syncing restore request (default/mp-etcd): prepare seed failed: failed to get reference EtcdCluster(default/mp-etcd): etcdclusters.etcd.database.coreos.com \"mp-etcd\" not found" pkg=controller
time="2019-02-22T13:41:10Z" level=error msg="error syncing restore request (default/mp-etcd.mp-temp): prepare seed failed: failed to get reference EtcdCluster(default/mp-etcd.mp-temp): etcdclusters.etcd.database.coreos.com \"mp-etcd.mp-temp\" not found" pkg=controller
time="2019-02-22T13:47:34Z" level=error msg="error syncing restore request (default/mp-etcd): prepare seed failed: failed to get reference EtcdCluster(default/mp-etcd): etcdclusters.etcd.database.coreos.com \"mp-etcd\" not found" pkg=controller
```

I tried the following modifications to the restore yaml:
- add the full path to the name of the cluster
- add a namespace spec in the metadata and / or the etcdCluster spec

Nothing worked. Any suggestions?

Thanks
Omer
