### ISSUE TITLE
TLS configuration: support kubernetes.io/tls type of secret. 

### ISSUE THREAD

**Issue by jgreat** [coreos/etcd-operator#2080]
Please consider supporting the the standard tls type of secret or add an option to specify the secret data key names in the config. This would allow for automatic cert generation with tools like cert-manager.

cert-manager generates tls secret objects like this: 

```yaml
kind: Secret
type: kubernetes.io/tls
apiVersion: v1
data:
  ca.crt: ...
  tls.crt: ...
  tls.key: ...
```
