### ISSUE TITLE
How can I specify "medium: Memory" and "sizeLimit: 5Gi" in the code?

### ISSUE THREAD

**Issue by dperique** [coreos/etcd-operator#2088]
I would like to be able to use emptyDir (currently the default), but I'd also like the volume to use tmpfs with 5Gig RAM (`emptyDir.medium=Memory` and `emptyDir.sizeLimit=5Gi`).

The yaml would be like this:

```
      volumes:
      - name: etcd-data
        emptyDir:
          medium: Memory
          sizeLimit: "5Gi"
```

An option to do this would be great as already mentioned in #2053.

I'm ok if an etcd-operator dev (or anyone) can provide clues for where we can specify `medium` and `sizeLimit` in the code.
