### ISSUE TITLE
backup-operator - ABS - backupPolicy - maxBackups doesn't cleanup old backup blobs

### ISSUE THREAD

**Issue by rhollins** [coreos/etcd-operator#2144]
Backup operator ignoring maxbackups setting and creating bobs withotu deleting old one.
blob format: etcd.backup_v3_2019-12-15-15:57:59

etcdbackup definintion:

```
apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdBackup"
metadata:
  name: example-etcd-cluster-1-backup
  namespace: admin
spec:
  backupPolicy:
    backupIntervalInSecond: 125
    maxBackups: 4  
  etcdEndpoints: ["http://example-etcd-cluster-1-client:2379"]
  storageType: ABS
  abs:
    # The format of the path must be: "<abs-container-name>/<path-to-backup-file>"
    path: etcd-backups/etcd.backup
    absSecret: abs-credentials
```

error in cr status (but backup still works):
```
status:
  Reason: 'failed to save snapshot (create etcd client failed: failed to get etcd
    client with maximum kv store revision: could not create an etcd client for the
    max revision purpose from given endpoints ([http://example-etcd-cluster-1-client:2379]))'
  etcdRevision: 3
  etcdVersion: 3.2.13
  lastSuccessDate: "2019-12-15T16:12:34Z"
  succeeded: false
```
