### ISSUE TITLE
AWS support for backup storage

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#341]
Currently we only support GCE ((kubernetes.io/gce-pd) PV as backup storage.

AWS support is a MUST HAVE to make etcd operator more accessible to cloud users. Specifically, we are planning to support types of storage on AWS for backup data.
- ~~EBS (kubernetes.io/aws-ebs) as PV. We have the PV code path there. It's not very hard to add support for it.~~ EBS is supported now.
- S3. We need to refactor the serverSnap() and writeSnap() path into interface and support other types of storage as well. Then we can implement S3 support for it.

**Comment by lachie83** [comment]
Dup of #340

**Comment by lachie83** [comment]
I can take a look at adding AWS-EBS support. On quick inspection it doesn't look terribly difficult

https://github.com/coreos/etcd-operator/blob/15cfbabda50c0a073276bbe1c6edf00fc4ec527c/pkg/util/k8sutil/backup.go#L40

**Comment by lachie83** [comment]
Also controller currently crashes waiting on PVC poll
```
time="2016-11-04T22:59:02Z" level=error msg="fail to poll PVC (etcd-cluster-pvc): timed out waiting for the condition" 
panic: timed out waiting for the condition

goroutine 16 [running]:
panic(0x18dc520, 0xc420101660)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/etcd-operator/pkg/controller.(*Controller).Run.func2(0xc420258180, 0xc42039df20)
	/go/src/github.com/coreos/etcd-operator/pkg/controller/controller.go:143 +0x4e4
created by github.com/coreos/etcd-operator/pkg/controller.(*Controller).Run
	/go/src/github.com/coreos/etcd-operator/pkg/controller/controller.go:154 +0x2e9
```

**Comment by xiang90** [comment]
@lachie83 Can you file an issue for it separately? That is a bug we should fix.

**Comment by hongchaodeng** [comment]
@xiang90 @lachie83 

See https://github.com/coreos/etcd-operator/issues/305

**Comment by hongchaodeng** [comment]
@lachie83 
If you would like to fix the PVC poll issue, please let me know. Other than that, I will fix it by next week.

And sure, feel free to ping me when you have a PR for the AWS PV support.

**Comment by lachie83** [comment]
Took a look through the code and it is already implemented via the pv-provisioner arg. I've tested and it works on AWS. The only issue is that the default deployment doesn't have it by default. LMK how you would like to handle this and I can submit a PR.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: etcd-operator
    spec:
      containers:
      - name: etcd-operator
        image: quay.io/coreos/etcd-operator
        command: 
        - "/bin/sh"
        - "-c"
        - "/usr/local/bin/etcd-operator --pv-provisioner=kubernetes.io/aws-ebs"
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

```bash
kubectl get pods,pvc
NAME                                READY     STATUS    RESTARTS   AGE
po/etcd-cluster-0000                1/1       Running   0          57s
po/etcd-cluster-0001                1/1       Running   0          50s
po/etcd-cluster-0002                1/1       Running   0          34s
po/etcd-cluster-backup-tool-3bj8k   1/1       Running   0          51s
po/etcd-operator-649933782-cdn1c    1/1       Running   0          2m
NAME                   STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
pvc/etcd-cluster-pvc   Bound     pvc-c84c344b-a31a-11e6-a2ff-0295f91dc779   1Gi        RWO           57s
```
