### ISSUE TITLE
Allow customizing etcd podSpec by sourcing from podTemplate

### ISSUE THREAD

**Issue by aaronlevy** [coreos/etcd-operator#552]
In some cases, a user may want to customize the etcd pods which are created by the etcd-operator, but this is not currently possible, as the podSpec is hard-coded in the operator itself.

An example use case:

Adding a custom annotation, such as `checkpointer.alpha.coreos.com/checkpoint=true` so that the CoreOS pod-checkpointer will save local copies of the launched etcd pods.

This could be hard-coded in the etcd-operator spec - but there may be other use-cases for customization.

One option here would be to allow (maybe by flag) sourcing a podTemplate, which the user is responsible for creating, then the etcd-operator can use to make copies from.

Example podTemplate:

```
apiVersion: v1
kind: PodTemplate
metadata:
  name: etcd-pod
  namespace: kube-system
template:
  metadata:
    name: etcd-pod
    namespace: kube-system
    annotations:
      foo: bar
  spec:
      [...]
```

Then maybe source by flag:
```
etcd-operator --pod-template=kube-system/etcd-pod
```

Not sure if this is the right way forward, but I can foresee the need for users to make minor customizations to the launched etcd pods - and wanted to track this as an option
