### ISSUE TITLE
RBAC: document a policy for the operator

### ISSUE THREAD

**Issue by philips** [coreos/etcd-operator#619]
etcd-operator deployment example doesn't work on Tectonic installs by default because RBAC is in place. We need to have a step to set this up properly.

cc @ericchiang @rithujohn191

**Comment by philips** [comment]
Error:

```
E0106 17:42:32.378922       5 leaderelection.go:252] error retrieving endpoint: the server does not allow access to the requested resource (get endpoints etcd-operator)
```

**Comment by philips** [comment]
Here is my "run it as admin" solution just for now.

```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: etcd-operator
roleRef:
  apiVersion: rbac.authorization.k8s.io/v1alpha1
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
```

We should have a real policy like identity does, something like this (totally untested):

```
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: etcd-operator
rules:
- apiGroups:
  - etcd.coreos.com
  attributeRestrictions: null
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - extensions
  attributeRestrictions: null
  resources:
  - thirdpartyresources
  verbs:
  - create
```

**Comment by hongchaodeng** [comment]
@philips 
We encountered the same issue when migrating to k8s v1.5 on GCE.
See https://github.com/coreos/etcd-operator/issues/501#issuecomment-270286401

**Comment by hongchaodeng** [comment]
@philips
I'm not familiar with RBAC.
Do you know why do we have that error? What role is the operator when issuing the request? And what's the ACL for that?

**Comment by philips** [comment]
@hongchaodeng RBAC means that service accounts are locked down to certain actions. Essentially we need to define a role and then bind that role to the service account.

**Comment by hongchaodeng** [comment]
@philips 
Can you give me the access to the cluster of problem? I didn't reproduce this problem on GKE.

**Comment by eddieesquivel** [comment]
Hi Hongchao - i had a similar issue with our latest Tectonic 1.5.2 release. RBAC changed a tiny bit form 1.4.x to 1.5.x this is the cluster role binding I used to get around it:

`apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRoleBinding
metadata:
  name: etcd-operator
roleRef:
  apiVersion: rbac.authorization.k8s.io/v1alpha1
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
`

**Comment by hongchaodeng** [comment]
Quick sum-up:
- GKE doesn't have RBAC enabled, while Tectonic have RBAC enabled by default.
- If no service account is associated with a pod, it is by default "${namespace}/default".
- Default service account has zero permission.

As Brandon mentioned above, we need to figure out what resources and permissions we need for etcd operator.

**Comment by xiang90** [comment]
@hongchaodeng Yes. It is a documentatio issue. Also the operator should fail fast with reasonable logging if it does not have enough permission it needs.

**Comment by hongchaodeng** [comment]
As an update, this is the full list of resources we will access, verbs being coarse-grained now:
```yaml
apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: etcd-operator
rules:
- apiGroups:
  - etcd.coreos.com
  resources:
  - clusters
  verbs:
  - "*"
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - create
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - create
- apiGroups: [""] # The API group "" indicates the core API Group.
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups:
  - extensions
  resources:
  - replicasets
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["read"]

```
