### ISSUE TITLE
Backup status not showing up

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#823]
What happened?

Tried out `example-etcd-cluster-with-backup.yaml` and didn't see backup status even after minutes.

**Comment by xiang90** [comment]
fixed by https://github.com/coreos/etcd-operator/pull/824

**Comment by hongchaodeng** [comment]
For record, it looks like:
```yaml
  status:
    backupServiceStatus:
      backupSize: 0
      backups: 1
      recentBackup:
        creationTime: 2017-02-25T05:47:59.841311981Z
        size: 0.023468018
        timeTookInSecond: 1
        version: 3.1.0
```
