### ISSUE TITLE
improvement on ready/unready member status

### ISSUE THREAD

**Issue by hongchaodeng** [coreos/etcd-operator#878]
Currently the ready members status looks like:
```
readyMembers:
- ...
reason: ""
...
unreadyMembers:
- ...
```

This doesn't look good. We should improve it by grouping them:
```
members:
  ready:
  -  ...
  unready:
  - ...
```
