### ISSUE TITLE
use FQDN for addressing etcd member pods

### ISSUE THREAD

**Issue by colhom** [coreos/etcd-operator#901]
Right now we're using pod IP, which means the only way to do any sort of x509 validation is via IP SANS. This makes assigning x509 identities to cluster pods a real pain, and needs to get fixed in advance of further static cluster TLS work.

  * Neither pod or service IP addresses are really reservable in Kubernetes. Which means you can't create the certificate until after the pod/service is created, which means you can't really pre-sign certificates in any way and still do meaningful metadata validation.

  * The certificate will not be transferable if that etcd node finds itself at a new IP

  * There's no way to sign a certificate for an open-ended group of addresses. So you have to account for all possible hostnames when you sign the cert, which again is problematic. Using DNS you can sign a cert for `*.xxxx.svc.cluster.local`, which is in plain english "any service address in the xxxx kubernetes namespace". This is *really critical* stuff to be able to express to `etcd-operator` from the get-go.

To get past these problems, we need to make sure `etcd-operator`, `backup` and all the etcd member pods *only* address each other via FQDN. For example:

`https://etcd-cluster-0002.my-cluster.my-namespace.svc.cluster.local`

This provides some much-needed flexibility to the end user, such as the ability to sign a generic certificate for all etcd member nodes in a reasonable way. Using IP SANS, this wouldn't really be possible as we would have to know the member IP addresses ahead of time.

A wildcard certificate could be generated for `*.my-cluster.my-namespace.svc.cluster.local`, but that wildcard is restricted to only validate for etcd member endpoints running in `my-namespace` on a Kubernetes cluster.

We don't even need to add a service per etcd member pod, as it appears we can directly expose the pod IP via DNS A records with `pod.beta.kubernetes.io/hostname` and `pod.beta.kubernetes.io/subdomain` annotations. 

\cc @hongchaodeng @ericchiang

**Comment by hongchaodeng** [comment]
How can we create a service like "etcd-cluster-0002.my-cluster"?

**Comment by colhom** [comment]
@hongchaodeng https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-records-and-hostname-based-on-pods-hostname-and-subdomain-fields

**Comment by ericchiang** [comment]
@hongchaodeng This would require the etcd operator to generate a unique service for each member (don't know if you could use endpoints instead). Per conversation in #899 I think creating predictable names for the members is a requirement for static TLS. How else would the admin know what common name or SANs to supply?

**Comment by hongchaodeng** [comment]
@colhom

I don't think there is any way to create a service `etcd-cluster-0002.my-cluster` . Please provide a service yaml to correct me.

@ericchiang 
I think you are suggesting reserved names/IPs. But from what I read on top comment this issue is about wildcard domain names like `*.my-cluster.my-namespace.svc.cluster.local` . That's something I'm confused and want to be clear about.

**Comment by bison** [comment]
I think what @colhom is saying is that with a service object for each cluster, and the correct annotations on the pods for that cluster, kube-dns will create DNS records in a way that makes it easy to either issue certs for each member up-front or just issue a wildcard.

Given a cluster called `my-etcd-cluster` and this YAML:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-etcd-cluster
spec:
  selector:
    cluster: my-etcd-cluster
  clusterIP: None
  ports:
    - name: client
      port: 2379
    - name: peer
      port: 2380
---
apiVersion: v1
kind: Pod
metadata:
  name: etcd-001
  labels:
    cluster: my-etcd-cluster
    name: etcd-001
spec:
  hostname: etcd-001
  subdomain: my-etcd-cluster
  containers:
  - image: quay.io/coreos/etcd:v3.1.5
    name: etcd
```

I can address that pod by name:
```sh-session
/ # ping -c1 etcd-001.my-etcd-cluster.default.svc.cluster.local
PING etcd-001.my-etcd-cluster.default.svc.cluster.local (172.17.0.5): 56 data bytes
64 bytes from 172.17.0.5: seq=0 ttl=64 time=0.399 ms
...
```
