### ISSUE TITLE
How can I specify volumes spec?

### ISSUE THREAD

**Issue by junghoahnsc** [coreos/etcd-operator#957]
Hello,

I'm trying to deploy etcd cluster in GKE. I created a node pool with SSD and I think
I need to specify volumes spec to use it like

```
volumes:
   - name: etcd-data
      hostPath:
          path: /mnt/disks/ssd0
```

But I couldn't find any way to specify this from examples. How can I do that?

Thanks,
